image: topocourse/topocourse
stages:
  - build
  - deploy


execute_ipynbs:
  stage: build
  script:
    - jupyter-book build .
    # Workaround of https://github.com/executablebooks/MyST-NB/issues/287
    - cp _static/mystnb.css _build/html/_static/
  artifacts:
    paths:
      - _build/html
    expire_in: 7d
  cache:
    - key: global
      paths:
        - _build/


mirror to github:
  stage: build
  allow_failure: true
  only:
    - branches@qt/topocm
  variables:
    REPOS: "git@github.com:topocm/topocm_content.git"
  before_script:
    - HOSTS=$(for REPO in $REPOS; do echo ${REPO%:*} | cut -d'@' -f2; done)
    - mkdir ~/.ssh && chmod 700 ~/.ssh
    - for HOST in $HOSTS; do ssh-keyscan $HOST >> ~/.ssh/known_hosts; done
    - echo "$PUSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  after_script:
    - rm -rf ~/.ssh
  script:
    - ORIGIN_URL=$(git config --get remote.origin.url)
    - cd $(mktemp -d); git clone --bare $ORIGIN_URL .
    - for REPO in $REPOS; do git push --mirror $REPO; done


.upload_website: &upload_website
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh && ssh-keyscan tnw-tn1.tudelft.net >> ~/.ssh/known_hosts
    - echo $WEBSITE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  script:
    - "rsync -ravz _build/html/* $USER@tnw-tn1.tudelft.net:"
  after_script:
    - rm -rf ~/.ssh


upload test website:
  <<: *upload_website
  environment: test
  only:
    - branches@qt/topocm
  except:
    - master@qt/topocm
  variables:
    USER: topocm-test


upload main website:
  <<: *upload_website
  environment: published
  only:
    - master@qt/topocm
  variables:
    USER: topocm
