image: topocourse/topocourse
stages:
  - build
  - deploy


execute_ipynbs:
  stage: build
  script:
    - jupyter-book build .
    # Workaround of https://github.com/executablebooks/MyST-NB/issues/287
    - cp _static/mystnb.css _build/html/_static/
  artifacts:
    paths:
      - _build/html
    expire_in: 7d
  cache:
    - key: global
      paths:
        - _build/


.upload_website: &upload_website
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh && ssh-keyscan tnw-tn1.tudelft.net >> ~/.ssh/known_hosts
    - echo $WEBSITE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  script:
    - "rsync -ravz _build/html/* $USER@tnw-tn1.tudelft.net:"
  after_script:
    - rm -rf ~/.ssh


upload test website:
  <<: *upload_website
  environment: test
  only:
    - branches@qt/topocm
  except:
    - master@qt/topocm
  variables:
    USER: topocm-test


upload main website:
  <<: *upload_website
  environment: published
  only:
    - master@qt/topocm
  variables:
    USER: topocm
